{% set name = "snoopy-log-collator" %}
{% set version = "0.7.2" %}
{% set sha256 = "946611344daf756ef431a95c7698a332e2ed22dbc7c684a548e5ad4e173ccf6b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py2k or win]
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - snoopy-log-collator = snoopy_log_collator.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive

  run:
    - python
    - pendulum
    - pytoml
    - setuptools

test:
  imports:
    - snoopy_log_collator
  commands:
    - snoopy-log-collator --help

about:
  home: https://github.com/tesujimath/snoopy-log-collator
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Collate logfiles from snoopy logger'
  description: |
    Snoopy-log-collator collates the log files from snoopy, producing a
    summary of what programs have been run on the system, when, and by whom.  The
    output comprises a number of files, one per command invoked, each being a list
    of invocation instances.
  dev_url: https://github.com/tesujimath/snoopy-log-collator

extra:
  recipe-maintainers:
    - tesujimath
