appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TSDuR3RlT0q8ah37p/95Y7fAxwTRKK+AH69v2YPrA+oOBRwu7vMzGKE4iO+kXwo1IwryN35kH3JPieGsxZ0zFWasCVWz+Y8mUu8DPVQmCvZP36nJgJHrzaYX+5Xu7CejjT7EGKsU3z6ZhTHiBVZzKq85XrsieQ3j+TLyjPX00ttL783PoJ27GUvl50g/QkOCJib8L3HSzOPx9L8z1g+EuD7s9m5KN/urv84kSFSnZxRja7s5gwKw1POkH5WWocfXQ9AI5jCfHFFijBUN8YL1WMPPxlEbG6AJlPTblo4y5TwGlUfUNLRjdRJUKBXb/LdAE7hTY3/39hUE8+k/OJ2E6UrahJMYiSM5Z1DoZ/CQwjIoIt0SKCgl1qrFUv93rdxS5WPIgMXShpnIgpjPwrOWbIr0g6R826SeCWA20fPX3yqz0rHtkGT+0tBWK0k2OA0gs2TW0kHmMVWz+Iiro8W9SZ760YGpbi6xXQvqGGk8uKhKtfioj9v+rqp4W0XJDLwhbdG4ZLl/ZZ4nOVu5bNQo0Ux33bn1tVz3zGQUJCGFfgHKjZFxOG3kBb9rCV90dbOAmxeC4LoU5csFMbXNU4SLOsbsRXCgY/+lbMFQ1mLlVAsJAcmX9GM8/e5DSYl97zgZgtD9o5yl4nCPdAarqxQUqCtHyLE/q80llArpX7QqV/o=}
