travis:
  secure:
    BINSTAR_TOKEN: V95GjNc8kXE6WWorW6Q9UeZH6Q9UpaUBgccZ7DLPdo2/lNzHF7FRSXQ/mAE1AkdvS3APlFEzDG99s0o1dVoaBojXEsghc0Ua4927cs4LP6YMAA5U6y4sc+/sbhSAgaSl+hI7KHO4To9mEnXQtCEoi9KBpLc8QhAoYEEfIy26fpQk5F7yj02Xix6NGqKYVs7PwS9076sExIINVTAIqzf1E6efxVzTgLuTnTUKnDw8G4iyLRro7hXizTkeahYcnVJzqsfXkk5KFaZWZBjgRlUPumGUKQWsV9XJtqQ+sOrYb05LeF4XnodlvpPverGhuGmMh9lKcjkHJ8JzOCw6XrpGzNct9C28Fsc4ydismCGPiTqt1ld+0QZinZIU6iAFhqQ3uWAse0cUmfTvkkVVX5lBZUp6Hh3Eq0W6iUW9Fs39TsSWUV6/naWwNn+ws1vCgpJ4RZai9baj9jeRE/idquYUW4/cYBQSdIWs/8UglITpHZpPEK6npMDMRma3/p4S4x3GnDssQJzQyZ7Sj1Xe8J+gDj8VXodNx6EWwb8/a9BPUn+qANNbUgVJuiJDdiRFQJpKydZ9qsiG3pN/daCplGbnNaGVMRK6pwImRGxV5cAFYFkz586R0W8XSBJC+8bgiKEvDt54+VQgRTBulJeHPNRMICSOcHmgOLidARzGsEv745g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
