travis:
  secure:
    BINSTAR_TOKEN: Iez7kOYRdrV3zAAlEbv58IbwAvkGC1J0NcmqsmllJvkLnx9x6MhY5HEhlBLdHaGLsWZxssNNqtv8YOr3Pbey60KxtZYwwzkavBoxSpJkkir8uUyyrxn45ynCNRDHiHTGL4AT2L6D4ezsMN6zILJNCPJOSVcNmRluil+thcCkt6TawqD7bcVcQYULORavhh87mtwAd4dy5e1pwAXvSRkt588QfyNWHcju9CCkP2rFHgqgVBWJH7rv4P0wu/Lrp0FPxeM24mcHCsExdphG4SEw2BwvlPMWff2ROkKkh5NClp47JWQnIrUb3GhLellWfsNfcBufTbNoXrxSoX4y5XL9FW/i7ZyXVwer7sekdrue+JG7JMae18HUUF0QKx+iJxVnPBzEN+r3f4LVO1zpHENkLpbP2PU/B/aBwo7LRPQp+GIPM6sG680rWprzyywSiWcVO7PV2Kolcj2V5Vk1PAOlfEObhMtWCn42GtENubglRu7kdubPcpTobRyusZfl/ouktiN5Hl1VDwgHEwt2yBJyDIZiZqHyXpq9Y4CA189sEo1mPURltYRMk+5RcZ4vITqcm+PkbUTnQsDMCnM6xgPQ3RosQUfDBco3ei0WKqbn8hb4zYO2egS28W9Kxvg8SXQ+610aq1BLWYq/cMoYlsSMicm1F3R3a0I89RnKGesrLMA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
